sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7
    - hhvm

install:
    - composer self-update
    - composer --prefer-source install

script:
    - ./vendor/bin/phpcs -p --extensions=php --standard=ruleset.xml src
    - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
    - ./vendor/bin/coveralls -v

matrix:
    allow_failures:
        - php: hhvm
